### PR TITLE
Revert "Improved no_usable_ruby() test"

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Reverts Homebrew/install#338
Fixes https://github.com/Homebrew/install/issues/342

### CODE REVIEW

**Comment by maxim-belkin** [comment]
we need to add `IFS=$' \t\n' # Restore IFS to its default value` before `return 1` too.

**Comment by MikeMcQuaid** [comment]
@maxim-belkin Please open a pull request for that or any other refactoring given it wasn't there before this revert.

**Comment by gromgit** [comment]
Alternative 1: since process substitutions are supported in Bash 3, the pipeline can be replaced as follows:
```
no_usable_ruby() {
  local ruby_exec
  while read -r ruby_exec; do
    if test_ruby "$ruby_exec"; then
      return 1
    fi
  done < <(which -a ruby)
  return 0
}
```
Alternative 2: Setting `shopt -s lastpipe` keeps the pipeline's last command line in the current shell process, so my original patch would work as-is, and it has no effect on the only other pipeline in `install.sh`. (I actually have that in almost all my scripts for that reason, but forgot that it's not in `install.sh`.)

**Comment by maxim-belkin** [comment]
Re alternative 1: yes, this works.
Re alternative 2: `lastpipe` appeared in Bash 4.2

**Pull request merged**
