### PR TITLE
Refactor: command as array

### PR DESCRIPTION
**Pull request by XuehaiPan**
Use arrays to store command lists for commonly used commands to make them more extendable. See #581.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@XuehaiPan Does this work as expected on Bash 3? Just checking.

**Comment by XuehaiPan** [comment]
Bash 3 does not support syntax `+=`:

```bash
var="foo"
var+="bar"       # Bash 4+
var="${var}bar"  # Bash 3

arr=()
arr+=("foo")             # Bash 4+
arr=("${arr[@]}" "foo")  # Bash 3
```

With `set -u`, we don't allow unbound variables and arrays (reference if empty). It will make the line so long to be Bash 3 compatible:

```bash
array_with_very_long_name=()
array_with_very_long_name+=("foo")  # Bash 4+

# Bash 3 with `set -u`
array_with_very_long_name=("${array_with_very_long_name[@]+"${array_with_very_long_name[@]}"}" "foo")
```

**Review by Rylan12 — COMMENTED** [review]
Is there a functional reason why arrays are better for us to use?

I'm not opposed to these changes but I'm not sure it increases clarity very much, and I don't think it's more elegant because we need to add lots of `[@]`s.

**Comment by carlocab** [comment]
I think the primary benefit of using arrays is to be able to use the `foo+=("bar")` syntax, but now we don't even have that.

**Comment by XuehaiPan** [comment]
The main motivation is to always have quotes around variable substitutions.

There was a mistake to use a string to store command line arguments but over quoted in #581.

The `SUDO` variable is a string rather than an array. When expand it as command line arguments, it shouldn't be quoted. (line 153, 155)

https://github.com/Homebrew/install/blob/8d46165bacced8e11230bbc1eca332236b59c17a/install.sh#L142-L158

**Comment by gromgit** [comment]
> Is there a functional reason why arrays are better for us to use?

Arrays can be expanded safely with `"${array[@]}"`, which doesn't do further word splitting after expansion. This helps prevent breakage with pathnames containing spaces, among other things. (I don't think there's much chance of that in Homebrew environs, but it doesn't hurt to play it safe.)

Constructing safe command invocations through array construction is in fact a Bash best-practice. Not sure why I didn't do that when I first did the script conversions from Ruby. Mea culpa. :man_facepalming:

**Comment by carlocab** [comment]
> Arrays can be expanded safely with `"${array[@]}"`, which doesn't do further word splitting after expansion. This helps prevent breakage with pathnames containing spaces, among other things.

I don't think there's any risk of that with the commands we're replacing, but I suppose it would be good to start with the pattern for others to follow in case something does get added that needs to handle word splitting correctly.

**Comment by XuehaiPan** [comment]
> I think the primary benefit of using arrays is to be able to use the `foo+=("bar")` syntax, but now we don't even have that.

Updated in https://github.com/Homebrew/install/pull/594#issuecomment-964357610. I think we can assume users always have bash 3.1+, which was released in 2006.

**Comment by XuehaiPan** [comment]
Is there a way to specify the bash version (3.2 etc.) in the GitHub Action?

```
- name: Bash 3.2 Syntax
  if: runner.os != 'windows'
  shell: bash 3.2
  run: |
    bash -u -n install.sh
    bash -u -O extglob -n uninstall.sh
```

**Comment by MikeMcQuaid** [comment]
> Is there a way to specify the bash version (3.2 etc.) in the GitHub Action?

If you use `/usr/bin/bash` on macOS: it'll be Bash 3.x.

> Arrays can be expanded safely with `"${array[@]}"`, which doesn't do further word splitting after expansion. This helps prevent breakage with pathnames containing spaces, among other things. (I don't think there's much chance of that in Homebrew environs, but it doesn't hurt to play it safe.)

Seems reasonable to me 👍🏻

**Comment by MikeMcQuaid** [comment]
Thanks again @XuehaiPan!

**Pull request merged**
