### PR TITLE
install: tweak constants.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Rename and freeze them for future changes.

### CODE REVIEW

**Comment by DomT4** [comment]
Seems reasonable.

**Comment by ilovezfs** [comment]
Would it be worth warning about the deprecation if we see the old variable defined in the environment?

**Comment by MikeMcQuaid** [comment]
@ilovezfs We're not actually doing anything with the environment here, just changing naming within this file.

**Comment by ilovezfs** [comment]
@MikeMcQuaid oh.

**Pull request merged**
