### PR TITLE
Allow install to use the CommandLineTools bundled with Xcode

### LINKED ISSUE #206: Headless Xcode Command Line Tools installation failed on 10.14
We have an automated Jenkins job that sets up machines by installing Homebrew on them. It started failing recently.

Reproduction:
1. Have a fresh installation of macOS Mojave (tested with 10.14.4)
2. Run `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

Expected outcome:
Homebrew installs successfully in interactive shell and non-interactive shell

Actual outcome:
_In interactive shell_
Screenshot 2019-06-04 at 17 50 40

_In non-interactive shell_
```
[2019-06-04T14:42:20.932Z] Installing homebrew
[2019-06-04T14:42:21.189Z] ==> This script will install:
[2019-06-04T14:42:21.189Z] /usr/local/bin/brew
[2019-06-04T14:42:21.189Z] /usr/local/share/doc/homebrew
[2019-06-04T14:42:21.189Z] /usr/local/share/man/man1/brew.1
[2019-06-04T14:42:21.189Z] /usr/local/share/zsh/site-functions/_brew
[2019-06-04T14:42:21.189Z] /usr/local/etc/bash_completion.d/brew
[2019-06-04T14:42:21.189Z] /usr/local/Homebrew
[2019-06-04T14:42:21.189Z] ==> The following existing directories will be made group writable:
[2019-06-04T14:42:21.189Z] /usr/local/lib
[2019-06-04T14:42:21.189Z] /usr/local/lib/pkgconfig
[2019-06-04T14:42:21.189Z] ==> The following existing directories will have their owner set to anka:
[2019-06-04T14:42:21.189Z] /usr/local/lib
[2019-06-04T14:42:21.189Z] /usr/local/lib/pkgconfig
[2019-06-04T14:42:21.189Z] ==> The following existing directories will have their group set to admin:
[2019-06-04T14:42:21.189Z] /usr/local/lib
[2019-06-04T14:42:21.189Z] /usr/local/lib/pkgconfig
[2019-06-04T14:42:21.189Z] ==> The following new directories will be created:
[2019-06-04T14:42:21.189Z] /usr/local/bin
[2019-06-04T14:42:21.189Z] /usr/local/etc
[2019-06-04T14:42:21.189Z] /usr/local/include
[2019-06-04T14:42:21.189Z] /usr/local/sbin
[2019-06-04T14:42:21.189Z] /usr/local/share
[2019-06-04T14:42:21.189Z] /usr/local/var
[2019-06-04T14:42:21.189Z] /usr/local/opt
[2019-06-04T14:42:21.189Z] /usr/local/share/zsh
[2019-06-04T14:42:21.189Z] /usr/local/share/zsh/site-functions
[2019-06-04T14:42:21.189Z] /usr/local/var/homebrew
[2019-06-04T14:42:21.189Z] /usr/local/var/homebrew/linked
[2019-06-04T14:42:21.189Z] /usr/local/Cellar
[2019-06-04T14:42:21.189Z] /usr/local/Caskroom
[2019-06-04T14:42:21.189Z] /usr/local/Homebrew
[2019-06-04T14:42:21.189Z] /usr/local/Frameworks
[2019-06-04T14:42:21.189Z] ==> The Xcode Command Line Tools will be installed.
[2019-06-04T14:42:21.189Z] ==> /usr/bin/sudo /bin/chmod u+rwx /usr/local/lib /usr/local/lib/pkgconfig
[2019-06-04T14:42:21.189Z] ==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/lib /usr/local/lib/pkgconfig
[2019-06-04T14:42:21.189Z] ==> /usr/bin/sudo /usr/sbin/chown anka /usr/local/lib /usr/local/lib/pkgconfig
[2019-06-04T14:42:21.445Z] ==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/lib /usr/local/lib/pkgconfig
[2019-06-04T14:42:21.445Z] ==> /usr/bin/sudo /bin/mkdir -p /usr/local/bin /usr/local/etc /usr/local/include /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
[2019-06-04T14:42:21.445Z] ==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/bin /usr/local/etc /usr/local/include /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
[2019-06-04T14:42:21.445Z] ==> /usr/bin/sudo /bin/chmod 755 /usr/local/share/zsh /usr/local/share/zsh/site-functions
[2019-06-04T14:42:21.445Z] ==> /usr/bin/sudo /usr/sbin/chown anka /usr/local/bin /usr/local/etc /usr/local/include /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
[2019-06-04T14:42:21.445Z] ==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/bin /usr/local/etc /usr/local/include /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
[2019-06-04T14:42:21.701Z] ==> /usr/bin/sudo /bin/mkdir -p /Users/anka/Library/Caches/Homebrew
[2019-06-04T14:42:21.701Z] ==> /usr/bin/sudo /bin/chmod g+rwx /Users/anka/Library/Caches/Homebrew
[2019-06-04T14:42:21.701Z] ==> /usr/bin/sudo /usr/sbin/chown anka /Users/anka/Library/Caches/Homebrew
[2019-06-04T14:42:21.701Z] ==> Searching online for the Command Line Tools
[2019-06-04T14:42:21.701Z] ==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
[2019-06-04T14:42:43.596Z] ==> Downloading and installing Homebrew...
[2019-06-04T14:42:43.596Z] xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
[2019-06-04T14:42:43.596Z] Failed during: git init -q
script returned exit code 1
```
Also, the following popup is visible on the machine:
Screenshot 2019-06-04 at 17 44 55

Here is the non-interactive output from the 8th of May when it was still working correctly:
```
20:31:15  Installing homebrew
20:31:16  ==> This script will install:
20:31:16  /usr/local/bin/brew
20:31:16  /usr/local/share/doc/homebrew
20:31:16  /usr/local/share/man/man1/brew.1
20:31:16  /usr/local/share/zsh/site-functions/_brew
20:31:16  /usr/local/etc/bash_completion.d/brew
20:31:16  /usr/local/Homebrew
20:31:16  ==> The following existing directories will be made group writable:
20:31:16  /usr/local/lib
20:31:16  /usr/local/lib/pkgconfig
20:31:16  ==> The following existing directories will have their owner set to anka:
20:31:16  /usr/local/lib
20:31:16  /usr/local/lib/pkgconfig
20:31:16  ==> The following existing directories will have their group set to admin:
20:31:16  /usr/local/lib
20:31:16  /usr/local/lib/pkgconfig
20:31:16  ==> The following new directories will be created:
20:31:16  /usr/local/bin
20:31:16  /usr/local/etc
20:31:16  /usr/local/include
20:31:16  /usr/local/sbin
20:31:16  /usr/local/share
20:31:16  /usr/local/var
20:31:16  /usr/local/opt
20:31:16  /usr/local/share/zsh
20:31:16  /usr/local/share/zsh/site-functions
20:31:16  /usr/local/var/homebrew
20:31:16  /usr/local/var/homebrew/linked
20:31:16  /usr/local/Cellar
20:31:16  /usr/local/Caskroom
20:31:16  /usr/local/Homebrew
20:31:16  /usr/local/Frameworks
20:31:16  ==> The Xcode Command Line Tools will be installed.
20:31:16  ==> /usr/bin/sudo /bin/chmod u+rwx /usr/local/lib /usr/local/lib/pkgconfig
20:31:16  ==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/lib /usr/local/lib/pkgconfig
20:31:17  ==> /usr/bin/sudo /usr/sbin/chown anka /usr/local/lib /usr/local/lib/pkgconfig
20:31:17  ==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/lib /usr/local/lib/pkgconfig
20:31:17  ==> /usr/bin/sudo /bin/mkdir -p /usr/local/bin /usr/local/etc /usr/local/include /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
20:31:17  ==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/bin /usr/local/etc /usr/local/include /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
20:31:17  ==> /usr/bin/sudo /bin/chmod 755 /usr/local/share/zsh /usr/local/share/zsh/site-functions
20:31:17  ==> /usr/bin/sudo /usr/sbin/chown anka /usr/local/bin /usr/local/etc /usr/local/include /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
20:31:17  ==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/bin /usr/local/etc /usr/local/include /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
20:31:17  ==> /usr/bin/sudo /bin/mkdir -p /Users/anka/Library/Caches/Homebrew
20:31:17  ==> /usr/bin/sudo /bin/chmod g+rwx /Users/anka/Library/Caches/Homebrew
20:31:17  ==> /usr/bin/sudo /usr/sbin/chown anka /Users/anka/Library/Caches/Homebrew
20:31:17  ==> Searching online for the Command Line Tools
20:31:17  ==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
20:31:33  ==> Installing Command Line Tools (macOS Mojave version 10.14) for Xcode-10.2
20:31:33  ==> /usr/bin/sudo /usr/sbin/softwareupdate -i Command\ Line\ Tools\ (macOS\ Mojave\ version\ 10.14)\ for\ Xcode-10.2
20:31:33  Software Update Tool
20:31:33  
20:31:33  
20:31:37  Downloading Command Line Tools (macOS Mojave version 10.14) for Xcode
20:31:37  Downloaded Command Line Tools (macOS Mojave version 10.14) for Xcode
20:32:34  Installing Command Line Tools (macOS Mojave version 10.14) for Xcode
20:32:34  Done with Command Line Tools (macOS Mojave version 10.14) for Xcode
20:32:34  Done.
20:32:34  ==> /usr/bin/sudo /bin/rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
20:32:34  ==> /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
20:32:34  ==> Downloading and installing Homebrew...
20:32:41  From https://github.com/Homebrew/brew
20:32:41   * [new branch]      master     -> origin/master
[...]
20:32:41   * [new tag]         2.1.2      -> 2.1.2
20:32:41  HEAD is now at 37f4b9264 Merge pull request #6108 from Homebrew/dependabot/bundler/docs/unicode-display_width-1.6.0
20:32:46  ==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
20:32:46    https://github.com/Homebrew/brew#donations
20:32:49  ==> Tapping homebrew/core
20:32:49  Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
20:32:56  Checking out files:  78% (3945/5007)   
[...]
Checking out files: 100% (5007/5007), done.
20:33:11  Tapped 2 commands and 4775 formulae (5,032 files, 12.4MB).
20:33:12  Already up-to-date.
20:33:12  ==> Installation successful!
```

### PR DESCRIPTION
**Pull request by AndrewSB**
Maybe closes #206

I don't want to install the CommandLineTools on a machine that already has Xcode

### CODE REVIEW

**Comment by AndrewSB** [comment]
tested on my machine: 

```
asb@Andrews-MacBook-Pro ~ % /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/AndrewSB/install/patch-1/install)"
==> You are using macOS 10.15.
==> We do not provide support for this pre-release version.
This installation may not succeed.
After installation, you will encounter build failures and other breakages.
Please create pull requests instead of asking for help on Homebrew's
GitHub, Discourse, Twitter or IRC. As you are running this pre-release version,
you are responsible for resolving any issues you experience.

==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 124174 (delta 18), reused 45 (delta 17), pack-reused 124120
Receiving objects: 100% (124174/124174), 29.40 MiB | 1.16 MiB/s, done.
Resolving deltas: 100% (91005/91005), done.
From https://github.com/Homebrew/brew
 * [new branch]      master     -> origin/master
 * [new tag]         0.1        -> 0.1
 * [new tag]         0.2        -> 0.2
 * [new tag]         0.3        -> 0.3
 * [new tag]         0.4        -> 0.4
 * [new tag]         0.5        -> 0.5
 * [new tag]         0.6        -> 0.6
 * [new tag]         0.7        -> 0.7
 * [new tag]         0.7.1      -> 0.7.1
 * [new tag]         0.8        -> 0.8
 * [new tag]         0.8.1      -> 0.8.1
 * [new tag]         0.9        -> 0.9
 * [new tag]         0.9.1      -> 0.9.1
 * [new tag]         0.9.2      -> 0.9.2
 * [new tag]         0.9.3      -> 0.9.3
 * [new tag]         0.9.4      -> 0.9.4
 * [new tag]         0.9.5      -> 0.9.5
 * [new tag]         0.9.8      -> 0.9.8
 * [new tag]         0.9.9      -> 0.9.9
 * [new tag]         1.0.0      -> 1.0.0
 * [new tag]         1.0.1      -> 1.0.1
 * [new tag]         1.0.2      -> 1.0.2
 * [new tag]         1.0.3      -> 1.0.3
 * [new tag]         1.0.4      -> 1.0.4
 * [new tag]         1.0.5      -> 1.0.5
 * [new tag]         1.0.6      -> 1.0.6
 * [new tag]         1.0.7      -> 1.0.7
 * [new tag]         1.0.8      -> 1.0.8
 * [new tag]         1.0.9      -> 1.0.9
 * [new tag]         1.1.0      -> 1.1.0
 * [new tag]         1.1.1      -> 1.1.1
 * [new tag]         1.1.10     -> 1.1.10
 * [new tag]         1.1.11     -> 1.1.11
 * [new tag]         1.1.12     -> 1.1.12
 * [new tag]         1.1.13     -> 1.1.13
 * [new tag]         1.1.2      -> 1.1.2
 * [new tag]         1.1.3      -> 1.1.3
 * [new tag]         1.1.4      -> 1.1.4
 * [new tag]         1.1.5      -> 1.1.5
 * [new tag]         1.1.6      -> 1.1.6
 * [new tag]         1.1.7      -> 1.1.7
 * [new tag]         1.1.8      -> 1.1.8
 * [new tag]         1.1.9      -> 1.1.9
 * [new tag]         1.2.0      -> 1.2.0
 * [new tag]         1.2.1      -> 1.2.1
 * [new tag]         1.2.2      -> 1.2.2
 * [new tag]         1.2.3      -> 1.2.3
 * [new tag]         1.2.4      -> 1.2.4
 * [new tag]         1.2.5      -> 1.2.5
 * [new tag]         1.2.6      -> 1.2.6
 * [new tag]         1.3.0      -> 1.3.0
 * [new tag]         1.3.1      -> 1.3.1
 * [new tag]         1.3.2      -> 1.3.2
 * [new tag]         1.3.3      -> 1.3.3
 * [new tag]         1.3.4      -> 1.3.4
 * [new tag]         1.3.5      -> 1.3.5
 * [new tag]         1.3.6      -> 1.3.6
 * [new tag]         1.3.7      -> 1.3.7
 * [new tag]         1.3.8      -> 1.3.8
 * [new tag]         1.3.9      -> 1.3.9
 * [new tag]         1.4.0      -> 1.4.0
 * [new tag]         1.4.1      -> 1.4.1
 * [new tag]         1.4.2      -> 1.4.2
 * [new tag]         1.4.3      -> 1.4.3
 * [new tag]         1.5.0      -> 1.5.0
 * [new tag]         1.5.1      -> 1.5.1
 * [new tag]         1.5.10     -> 1.5.10
 * [new tag]         1.5.11     -> 1.5.11
 * [new tag]         1.5.12     -> 1.5.12
 * [new tag]         1.5.13     -> 1.5.13
 * [new tag]         1.5.14     -> 1.5.14
 * [new tag]         1.5.2      -> 1.5.2
 * [new tag]         1.5.3      -> 1.5.3
 * [new tag]         1.5.4      -> 1.5.4
 * [new tag]         1.5.5      -> 1.5.5
 * [new tag]         1.5.6      -> 1.5.6
 * [new tag]         1.5.7      -> 1.5.7
 * [new tag]         1.5.8      -> 1.5.8
 * [new tag]         1.5.9      -> 1.5.9
 * [new tag]         1.6.0      -> 1.6.0
 * [new tag]         1.6.1      -> 1.6.1
 * [new tag]         1.6.10     -> 1.6.10
 * [new tag]         1.6.11     -> 1.6.11
 * [new tag]         1.6.12     -> 1.6.12
 * [new tag]         1.6.13     -> 1.6.13
 * [new tag]         1.6.14     -> 1.6.14
 * [new tag]         1.6.15     -> 1.6.15
 * [new tag]         1.6.16     -> 1.6.16
 * [new tag]         1.6.17     -> 1.6.17
 * [new tag]         1.6.2      -> 1.6.2
 * [new tag]         1.6.3      -> 1.6.3
 * [new tag]         1.6.4      -> 1.6.4
 * [new tag]         1.6.5      -> 1.6.5
 * [new tag]         1.6.6      -> 1.6.6
 * [new tag]         1.6.7      -> 1.6.7
 * [new tag]         1.6.8      -> 1.6.8
 * [new tag]         1.6.9      -> 1.6.9
 * [new tag]         1.7.0      -> 1.7.0
 * [new tag]         1.7.1      -> 1.7.1
 * [new tag]         1.7.2      -> 1.7.2
 * [new tag]         1.7.3      -> 1.7.3
 * [new tag]         1.7.4      -> 1.7.4
 * [new tag]         1.7.5      -> 1.7.5
 * [new tag]         1.7.6      -> 1.7.6
 * [new tag]         1.7.7      -> 1.7.7
 * [new tag]         1.8.0      -> 1.8.0
 * [new tag]         1.8.1      -> 1.8.1
 * [new tag]         1.8.2      -> 1.8.2
 * [new tag]         1.8.3      -> 1.8.3
 * [new tag]         1.8.4      -> 1.8.4
 * [new tag]         1.8.5      -> 1.8.5
 * [new tag]         1.8.6      -> 1.8.6
 * [new tag]         1.9.0      -> 1.9.0
 * [new tag]         1.9.1      -> 1.9.1
 * [new tag]         1.9.2      -> 1.9.2
 * [new tag]         1.9.3      -> 1.9.3
 * [new tag]         2.0.0      -> 2.0.0
 * [new tag]         2.0.1      -> 2.0.1
 * [new tag]         2.0.2      -> 2.0.2
 * [new tag]         2.0.3      -> 2.0.3
 * [new tag]         2.0.4      -> 2.0.4
 * [new tag]         2.0.5      -> 2.0.5
 * [new tag]         2.0.6      -> 2.0.6
 * [new tag]         2.1.0      -> 2.1.0
 * [new tag]         2.1.1      -> 2.1.1
 * [new tag]         2.1.2      -> 2.1.2
 * [new tag]         2.1.3      -> 2.1.3
 * [new tag]         2.1.4      -> 2.1.4
HEAD is now at 80230eccf Merge pull request #6210 from lembacon/pkg-config-catalina
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 5001, done.
remote: Counting objects: 100% (5001/5001), done.
remote: Compressing objects: 100% (4792/4792), done.
remote: Total 5001 (delta 51), reused 791 (delta 16), pack-reused 0
Receiving objects: 100% (5001/5001), 4.01 MiB | 1.09 MiB/s, done.
Resolving deltas: 100% (51/51), done.
Tapped 2 commands and 4787 formulae (5,043 files, 12.5MB).
Already up-to-date.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Next steps:
- Run `brew help` to get started
- Further documentation: 
    https://docs.brew.sh
```

homebrew's version tried to install CommandLineTools:

```
asb@Andrews-MacBook-Pro ~ % /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> You are using macOS 10.15.
==> We do not provide support for this pre-release version.
This installation may not succeed.
After installation, you will encounter build failures and other breakages.
Please create pull requests instead of asking for help on Homebrew's
GitHub, Discourse, Twitter or IRC. As you are running this pre-release version,
you are responsible for resolving any issues you experience.

==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The Xcode Command Line Tools will be installed.

Press RETURN to continue or any other key to abort

```

**Comment by NorseGaud** [comment]
Super excited to get this in so we can build out brew automatically onto 10.14.5.

**Comment by Nezz** [comment]
Note that if you run xcode-select without CLT installed, it will prompt a popup in macOS to install CLT.

**Comment by microtherion** [comment]
What exactly do those packages need? Do they need particular tools, or the tools at a particular location?

**Comment by MikeMcQuaid** [comment]
> Do they need particular tools, or the tools at a particular location?

Both.

**Comment by AndrewSB** [comment]
I'm not going to update this for a while, since my new machine is set up. Might come back to revisit this, @anyone-else feel free to PR against my fork and I'll accept changes to make this a flag

**Comment by MikeMcQuaid** [comment]
Closing in favour of another PR then, thanks.

**Pull request closed without merging**
