### PR TITLE
Use `HOMEBREV_PREFIX` env variable if set

### PR DESCRIPTION
**Pull request by maarons**
I'd like to be able to easily install Homebrew to a custom location in
a non-interactive way (like Chef actually doing the work).  Current
method of editing the install file is not really suited for automated
use.

### CODE REVIEW

**Comment by ilovezfs** [comment]
If this were something we were going to support, I think it would need to be via a command-line switch and/or a configuration file.

**Comment by MikeMcQuaid** [comment]
We don't support installing outside /usr/local in the installer, sorry.

**Comment by maarons** [comment]
Any particular reason you don't want to support that?

**Comment by MikeMcQuaid** [comment]
People don't get binary packages (which means more issues get filed), some software doesn't exist.

**Comment by mareksapota-lyft** [comment]
@MikeMcQuaid got it.  Maybe the FAQ should get updated, it doesn't really discourage prefix use and it seems it should.

**Comment by maarons** [comment]
@MikeMcQuaid got it. Maybe the FAQ should get updated, it doesn't really discourage prefix use and it seems it should.

**Comment by MikeMcQuaid** [comment]
@maarons good idea but we already provide some gentle discouragement through the installer and the `brew doctor`. Thanks!

**Pull request closed without merging**
