### PR TITLE
Fix SUDO_ASKPASS support

### PR DESCRIPTION
**Pull request by johngun3**
Fixes issue https://github.com/Homebrew/install/issues/313. Fixes SUDO_ASKPASS support in the install script. Copied from https://github.com/Homebrew/install/pull/306

### CODE REVIEW

**Comment by johngun3** [comment]
@MikeMcQuaid Do I need to add sudo to the install test to get it to pass?

**Comment by johngun3** [comment]
Admittedly I'm not a very familiar with bash so I had to jigger with the changes from the other pull request to fully get it to work. I'm certainly open to any suggestions.

**Comment by MikeMcQuaid** [comment]
Looks good! Does this work for you locally? If so, I'm happy to merge this.

**Comment by johngun3** [comment]
Yes. I tested with and without the SUDO_ASKPASS variable specified.

**Comment by MikeMcQuaid** [comment]
Great, thanks @johngun3, nice work!

**Pull request merged**
