### PR TITLE
macOS Big Sur

### PR DESCRIPTION
**Pull request by fxcoudert**
Not yet ready for merging, to be shipped as soon as Big Sur ships
See also: https://github.com/Homebrew/brew/pull/9054

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> as soon as Big Sur ships

I don't think this can ship until at least https://github.com/Homebrew/brew/pull/9010 does and/or we have working homebrew-core CI.

**Comment by MikeMcQuaid** [comment]
Think we'll need to have some code that fails on ARM for now.

**Comment by MikeMcQuaid** [comment]
Think we'll need to have some code that fails on ARM for now.

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
This should not ship until we have working Big Sur CI. We cannot support what we do not have CI for.

**Comment by jamm1985** [comment]
@MikeMcQuaid  Is it ready to merge?

**Comment by MikeMcQuaid** [comment]
@jamm1985 Once https://github.com/Homebrew/brew/pull/9054 is in a tagged release.

**Review by MikeMcQuaid — APPROVED** [review]
Fine to 🚢 once we've released a new tag.

**Comment by MikeMcQuaid** [comment]
Thanks @fxcoudert!

**Pull request merged**
