### PR TITLE
install/uninstall: be less cryptic on failures

### PR DESCRIPTION
**Pull request by DomT4**
Closes Homebrew/homebrew#45692.
Closes Homebrew/homebrew#45733.

### CODE REVIEW

**Comment by DomT4** [comment]
CC @mikemcquaid @xu-cheng.

I'm sure the Ruby could be tidier, but it works well locally.

**Comment by mikemcquaid** [comment]
:+1:

**Comment by xu-cheng** [comment]
:+1:

**Comment by DomT4** [comment]
Thanks both :)

**Pull request merged**
