### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Danrancan**
1) Updated uninstall instructions to take ownership and execute the uninstall script "raw" file downloaded from github.
2) Updated uninstall instructions to appeal to noobs and those unfamiliar with the command line.

### CODE REVIEW

**Comment by itchyny** [comment]
Note that `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" -- --help` prints the help of the uninstaller.

**Comment by MikeMcQuaid** [comment]
I would suggest instead doing `/usr/bin/ruby ./uninstall --help` and then it can be a single step again.

**Comment by Danrancan** [comment]
I think just noting that `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" --help` one liner is probably the easiest for newbs and the most newb friendly.

**Comment by itchyny** [comment]
Please note that `-- --help`, not just `--help`.

**Comment by MikeMcQuaid** [comment]
Either is fine.

**Pull request closed without merging**
